version: '3'
services:
  remotemachine:
    build:
      context: ../
      dockerfile: ci/Dockerfile.testMachine
    volumes:
      - ../:/app/
    ports:
      - "2222:22"
    networks:
      network:
        ipv4_address: 10.10.10.10
    restart: always

  tests:
    image: rust:latest
    volumes:
      - ../:/app/
    depends_on:
      - remotemachine
    networks:
      - network


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.10.11