name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  pre_checks:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test Code
        if: github.event_name != 'schedule'
        run: docker compose -f ci/docker-compose.yml run tests ./app/ci/run_tests.sh

      - name: Lint Code
        if: github.event_name != 'schedule'
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings

      - name: Format Code
        if: github.event_name != 'schedule'
        run: |
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Check TODOs
        if: github.event_name != 'schedule'
        run: find ${GITHUB_WORKSPACE}/src -type f | xargs grep -nH "TODO\!" && exit 1 || exit 0

  build_package:
    needs: pre_checks
    runs-on: ubuntu-latest
    container: clux/muslrust
    steps:
      - uses: actions/checkout@v3

      - name: Build Package
        if: github.event_name != 'schedule'
        run: cargo build --release

      - name: Upload Artifact
        if: github.event_name != 'schedule'
        uses: actions/upload-artifact@v3
        with:
          name: crust
          path: target/x86_64-unknown-linux-musl/release/crust
