name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-code:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: docker compose -f ci/docker-compose.yml run tests ./app/ci/run_tests.sh

  lint-code:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings

  format-code:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  todos:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: find ${CI_PROJECT_DIR}/src -type f | xargs grep -nH "TODO\!" && exit 1 || exit 0

  build_package:
    if: contains( github.ref, 'master')
    container: clux/muslrust
    runs-on: ubuntu-latest
    needs: [test-code,lint-code,format-code,todos]
    steps:
      - run: cargo build --release